# Generated by Django 2.1.2 on 2019-04-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('contact', models.IntegerField()),
                ('address', models.TextField(max_length=300)),
                ('department_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Health_Policy',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=30)),
                ('policy_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('time_duration', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_number', models.IntegerField()),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('no_of_family', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Home_Policy',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=30)),
                ('policy_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('time_duration', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_number', models.IntegerField()),
                ('rate_of_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rules', models.TextField(max_length=100)),
                ('benificial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Life_Policy',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=30)),
                ('policy_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('time_duration', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_number', models.IntegerField()),
                ('rate_of_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rules', models.TextField(max_length=100)),
                ('benificial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accidential_benifit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Motor_Policy',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=30)),
                ('policy_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('time_duration', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_number', models.IntegerField()),
                ('rate_of_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rules', models.TextField(max_length=100)),
                ('benificial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=30)),
                ('vehicle_no', models.IntegerField()),
                ('company', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Travel_Policy',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=30)),
                ('policy_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('time_duration', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_number', models.IntegerField()),
                ('rate_of_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rules', models.TextField(max_length=100)),
                ('benificial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geographic', models.CharField(max_length=30)),
                ('coverage', models.CharField(max_length=30)),
            ],
        ),
    ]
