# Generated by Django 2.1.2 on 2019-04-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motor_Policy',
            new_name='Car_Policy',
        ),
        migrations.DeleteModel(
            name='Travel_Policy',
        ),
    ]
