# Generated by Django 2.1.2 on 2019-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_auto_20190423_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_policy',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='health_policy',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='home_policy',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='life_policy',
            name='policy_id',
        ),
        migrations.AlterField(
            model_name='car_policy',
            name='policy_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='health_policy',
            name='policy_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='home_policy',
            name='policy_type',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='life_policy',
            name='policy_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
