# Generated by Django 2.1.2 on 2019-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_auto_20190424_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_policy',
            name='policy_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='home_policy',
            name='policy_type',
            field=models.CharField(max_length=30),
        ),
    ]
