# Generated by Django 2.1.2 on 2019-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_Premium',
            fields=[
                ('policy_holder_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('policy_payment_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy_number', models.IntegerField()),
                ('dd_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Take_Insurance',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=30)),
                ('policy_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('policy_duration', models.IntegerField()),
                ('policy_taking_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benificial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
